# Naming the workflow
name: Build and Deploy

# Defines the events that trigger the workflow
on:
  push:
  pull_request:
    branches: [develop, main]

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Step up JDK 21
        uses: actions/setup-java@v6
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn -B clean package

      - name: Upload build artifact
        uses: actions/upload-artifact@v6
        with:
          name: ecolely-service
          path: target/*.jar

  deploy:
    environment: dev
    name: Deploy to EC2
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v6
        with:
          name: ecolely-service
          path: ./

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.EC2_SSH_PRIVATE_KEY}}" > ~/.ssh/ec2.pem
          chmod 600 ~/.ssh/ec2.pem

      - name: Copy build artifact to EC2
        run: |
          scp \
           -i ~/.ssh/ec2.pem \
           -o StrictHostKeyChecking=no \
          *.jar \
          ${{ secrets.EC2_SSH_USER }}@${{ secrets.EC2_SSH_HOST }}:/opt/ecolely-service/app.jar